language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet restore src/
 - dotnet publish src/ -c Release -r linux-x64 -o ../publish/linux-x64
 - dotnet publish src/ -c Release -r linux-arm -o ../publish/linux-arm
 - dotnet publish src/ -c Release -r win7-x64 -o ../publish/win7-x64
after_success:
    "zip out.zip publish/**/* && curl -T out.zip -u $FTP_USER:$FTP_PASSWORD ftp://$DEPLOY_SERVER && curl -X HEAD http://$DEPLOY_SERVER:2100"
